name: generate-image-list
on:
  push:
    paths:
      - 'pic_utill/images/**'
      - 'pic_utill/scripts/gen-list.js'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node pic_utill/scripts/gen-list.js
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pic_utill/list.json
          git diff --cached --quiet || git commit -m "chore: auto update list.json"
          git push